---
- name: Make a POST call to API using prompt for password
  hosts: localhost
  vars:
    api_username: "your_api_username"  # You can also prompt for username if needed
  tasks:
    - name: Send POST request to API
      uri:
        url: 'https://example.com/api/endpoint'
        method: POST
        body: |
          {
            "key1": "value1",
            "key2": "value2"
          }
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Basic {{ api_username }}:{{ api_password | b64encode }}"
      register: result

    - name: Print the response
      debug:
        var: result
      no_log: true
