# templates/serviceaccount.yaml
{{- if eq .Values.environment "prod" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quay
  namespace: your-namespace
{{- end }}

# templates/role.yaml
{{- if eq .Values.environment "prod" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-binding-role
  namespace: your-namespace
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}

# templates/rolebinding.yaml
{{- if eq .Values.environment "prod" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc-binding-rolebinding
  namespace: your-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-binding-role
subjects:
- kind: ServiceAccount
  name: quay
  namespace: your-namespace
{{- end }}
